name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 7 */9 * *"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        runner: [ubuntu-latest]
        include:
          - python-version: "3.13"
            runner: macos-latest
          - python-version: "3.13"
            runner: windows-latest
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - uses: astral-sh/setup-uv@f731690a1dacb2f6393acc910887b8cda1a97789 # v3
        with:
          enable-cache: true

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Execute tests
        run: uv tool run tox -e ${{ matrix.python-version }}

  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: boidolr/actions/run-precommit@main
        env:
          UV_PYTHON: "3.13"
